---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - language-pack-ja
    - tree
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
