---
- name: add an apt key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
- name: add a repository into sources list
  apt_repository:
    repo: deb http://nginx.org/packages/ubuntu/ {{ codename }} nginx
    state: present
- name: add a source repository into sources list
  apt_repository:
    repo: deb-src http://nginx.org/packages/ubuntu/ {{ codename }} nginx
    state: present
- name: remove "nginx-common" package
  apt:
    name: nginx-common
    state: absent
- name: install "nginx" package
  apt:
    name: nginx
    state: present
    update_cache: yes
